trigger: none

pool: agents-dev

steps:

- task: CmdLine@2
  displayName: clone IWA DotNet   
  inputs:
    script: |
     git clone   https://github.com/fortify/IWA-DotNet
    workingDirectory: 'Gitleaks'

- task: CmdLine@2
  displayName: Get gitleaks
  inputs:
    script: |
      wget https://github.com/gitleaks/gitleaks/releases/download/v8.16.2/gitleaks_8.16.2_linux_x64.tar.gz
      tar xf gitleaks_8.16.2_linux_x64.tar.gz
      sudo mv gitleaks /usr/bin
    workingDirectory: 'Gitleaks'

- task: Bash@3
  displayName: Gitleaks Scan
  inputs:
    targetType: 'inline'
    script: |
      gitleaks detect --report-path gitleaks-report-bb.json --source . --verbose
      if [ $? -eq 1 ]; then 
      echo "Leaks or error encountered, but pipeline will continue"
      else
      exit $?
      fi
    workingDirectory: 'Gitleaks'

- task: PublishBuildArtifacts@1
  inputs:
    targetPath: 'gitleaks-report.json'
    ArtifactName: 'gitleaks-report-bb'
    publishLocation: 'Container'
